//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonteroExpressWF.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntidadDireccione
    {
        public EntidadDireccione()
        {
            this.Envios = new HashSet<Envio>();
            this.Envios1 = new HashSet<Envio>();
        }
    
        public int IdEntidadDireccion { get; set; }
        public Nullable<int> IdEntidad { get; set; }
        public string Direccion { get; set; }
        public int IdCiudad { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public bool PorDefecto { get; set; }
        public System.DateTime FechaIngreso { get; set; }
    
        public virtual Ciudade Ciudade { get; set; }
        public virtual Entidade Entidade { get; set; }
        public virtual ICollection<Envio> Envios { get; set; }
        public virtual ICollection<Envio> Envios1 { get; set; }
    }
}
