//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonteroExpressWF.DAL
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Entidade
    {
        public Entidade()
        {
            this.EntidadDirecciones = new HashSet<EntidadDireccione>();
        }
    
        public int IdEntidad { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdTipoDocumento { get; set; }
        public string NumDocumento { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ICollection<EntidadDireccione> EntidadDirecciones { get; set; }
        public virtual TiposDocumento TiposDocumento { get; set; }
    }
}
