//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonteroExpressWF.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envio
    {
        public Envio()
        {
            this.PaquetesEnvios = new HashSet<PaquetesEnvio>();
            this.TiposContenidosPaquetesEnvios = new HashSet<TiposContenidosPaquetesEnvio>();
        }
    
        public int IdEnvio { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> IdOficina { get; set; }
        public string AlbaranNum { get; set; }
        public Nullable<int> IdRemitenteDir { get; set; }
        public Nullable<int> IdDestinatarioDir { get; set; }
        public Nullable<int> IdSeguroEnvio { get; set; }
        public Nullable<int> IdEstadoEnvio { get; set; }
        public decimal Valor { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        public virtual EntidadDireccione EntidadDireccione { get; set; }
        public virtual EntidadDireccione EntidadDireccione1 { get; set; }
        public virtual EstadosEnvio EstadosEnvio { get; set; }
        public virtual Oficina Oficina { get; set; }
        public virtual SegurosEnvio SegurosEnvio { get; set; }
        public virtual ICollection<PaquetesEnvio> PaquetesEnvios { get; set; }
        public virtual ICollection<TiposContenidosPaquetesEnvio> TiposContenidosPaquetesEnvios { get; set; }
    }
}
