//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonteroExpressWF.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MonteroExpressEntities : DbContext
    {
        public MonteroExpressEntities()
            : base("name=MonteroExpressEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ciudade> Ciudades { get; set; }
        public virtual DbSet<EntidadDireccione> EntidadDirecciones { get; set; }
        public virtual DbSet<Entidade> Entidades { get; set; }
        public virtual DbSet<Envio> Envios { get; set; }
        public virtual DbSet<EstadosEnvio> EstadosEnvios { get; set; }
        public virtual DbSet<EstadosPaquete> EstadosPaquetes { get; set; }
        public virtual DbSet<Oficina> Oficinas { get; set; }
        public virtual DbSet<Pais> Paises { get; set; }
        public virtual DbSet<PaquetesEnvio> PaquetesEnvios { get; set; }
        public virtual DbSet<Provincia> Provincias { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SegurosEnvio> SegurosEnvios { get; set; }
        public virtual DbSet<TiposContenido> TiposContenidos { get; set; }
        public virtual DbSet<TiposContenidosPaquetesEnvio> TiposContenidosPaquetesEnvios { get; set; }
        public virtual DbSet<TiposDocumento> TiposDocumentos { get; set; }
        public virtual DbSet<TiposPaquete> TiposPaquetes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
