//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonteroExpressWF.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaquetesEnvio
    {
        public int IdPaqueteEnvio { get; set; }
        public Nullable<int> IdEnvio { get; set; }
        public int Cantidad { get; set; }
        public Nullable<int> IdTipoPaquete { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdEstadoPaquete { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> PrecioTotal { get; set; }
    
        public virtual Envio Envio { get; set; }
        public virtual EstadosPaquete EstadosPaquete { get; set; }
        public virtual TiposPaquete TiposPaquete { get; set; }
    }
}
