//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonteroExpressWF.DAL
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

[XmlRoot(ElementName="TiposDocumento")]
    
    public partial class TiposDocumento
    {
        public TiposDocumento()
        {
            this.Entidades = new HashSet<Entidade>();
        }
    [XmlAttribute(DataType="int",AttributeName = "IdTipoDocumento")]
        public int IdTipoDocumento { get; set; }
    [XmlAttribute(DataType = "string", AttributeName = "Descripcion")]
        public string Descripcion { get; set; }
    [XmlAttribute(DataType = "string", AttributeName = "Mascara")]
        public string Mascara { get; set; }
    [XmlAttribute(DataType = "date", AttributeName = "FechaIngreso")]
        public System.DateTime FechaIngreso { get; set; }
    [XmlAttribute(DataType = "boolean", AttributeName = "Activo")]
        public bool Activo { get; set; }
    [XmlElement(Type = typeof(ICollection<Entidade>), ElementName = "Entidades")]
        public virtual ICollection<Entidade> Entidades { get; set; }
    }
}
