//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonteroExpressWF.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposContenidosPaquetesEnvio
    {
        public int IdTipoContenidoPaqueteEnvio { get; set; }
        public Nullable<int> IdEnvio { get; set; }
        public Nullable<int> IdTipoContenido { get; set; }
    
        public virtual Envio Envio { get; set; }
        public virtual TiposContenido TiposContenido { get; set; }
    }
}
