//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonteroExpressWF.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public byte[] Contrasena { get; set; }
        public Nullable<bool> CambiarContrasena { get; set; }
        public Nullable<int> IdRol { get; set; }
        public bool Habilitado { get; set; }
        public System.DateTime FechaIngreso { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
